apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hello-world-http
spec:
  rules:
  - host: internal.path.to.argocd.io
    http:
      paths:
      - backend:
          service:
            name: simple-service
            port:
              number: 80
