apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: argocd-
commonLabels:
  variant: argocd
helmGlobals:
  chartHome: ../../base/charts

helmCharts:
  - name: stack-tech
    releaseName: stack-tech
    valuesInline:
      spec:
        project: argocd
        destination:
          server: https://4.212.8.55:6443
      nfsclient:
        enabled: false          
      prom2teams:
        connectors: 
        - teams : "https://charlesandre.webhook.office.com/webhookb2/5c49e775-13d2-4f6d-80b5-ba3f1651ebaf@38e68108-2383-4d82-a4b3-ac423a5e6218/IncomingWebhook/ed78864715e742888b91fb4181eaab87/dfd76bdb-37d4-4c4c-b907-6ea781954db5"
      kubePrometheusStack:
        enabled: true
      loki:
        enabled: true
      tempo:
        enabled: false
      opentelemetry:
        enabled: false
      neuvector:
        enabled: true
      bringmycar:
        enabled: false
      longhorn:
        enabled: true        
# patches:
#   - target:
#       kind: Application
#       name: .*traefik 
#     patch: |-
#       - op: replace
#         path: /spec/syncPolicy
#         value: {}         