apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: azure-pool1-
commonLabels:
  variant: azure-pool1
helmGlobals:
  chartHome: ../../base/charts

helmCharts:
  - name: stack-tech
    releaseName: stack-tech
    valuesInline:
      spec:
        project: azure-pool1
        destination:
          server: https://4.233.109.21:6443
      prom2teams:
        connectors: 
        - teams : "https://charlesandre.webhook.office.com/webhookb2/5c49e775-13d2-4f6d-80b5-ba3f1651ebaf@38e68108-2383-4d82-a4b3-ac423a5e6218/IncomingWebhook/8c89ebe05dff443391f7c465b1ed1dee/dfd76bdb-37d4-4c4c-b907-6ea781954db5"
      kubePrometheusStack:
        enabled: true
      loki:
        enabled: true
      tempo:
        enabled: true
      opentelemetry:
        enabled: true
# patches:
#   - target:
#       kind: Application
#       name: .*traefik 
#     patch: |-
#       - op: replace
#         path: /spec/syncPolicy
#         value: {}         