apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: azure-pool1-
commonLabels:
  variant: azure-pool1
helmGlobals:
  chartHome: ../../base/charts

helmCharts:
  - name: stack-tech
    releaseName: stack-tech
    valuesInline:
      spec:
        project: azure-pool1
        destination:
          server: https://4.233.109.21:6443
      prom2teams:
        connectors: 
        - teams : "https://charlesandre.webhook.office.com/webhookb3"
      kubePrometheusStack:
        enabled: true
      loki:
        enabled: true