apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
patches:
  - target:
      kind: Application
    patch: |-
      - op: replace
        path: /spec/project
        value: azure-pool1
      - op: replace 
        path: /spec/destination/server
        value: https://4.233.109.21:6443
namePrefix: azure-pool1-
commonLabels:
  variant: azure-pool1