{{- if eq .Values.k8s.flavor "rke2" }}
{{- if eq .Values.storageClass.name "longhorn" -}}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: {{ .Values.spec.project }}
  sources:
    - repoURL: https://github.com/longhorn/longhorn
      targetRevision: v1.6.0
      path: deploy/prerequisite
      directory:
        include: "{longhorn-iscsi-installation.yaml,longhorn-nfs-installation.yaml}"
    - repoURL: https://charts.longhorn.io/
      targetRevision: v1.6.0
      chart: longhorn
      helm:
        releaseName: longhorn
        valuesObject:
          preUpgradeChecker:
            jobEnabled: false
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: longhorn-system
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
{{- end }}
{{- end }}