spec:
  destination:
    server: https://kubernetes.default.svc
  project: default
k8s:
  flavor: rke2
storageClass:
  name: longhorn
prom2teams:
  connectors: 
  - teams : "https://charlesandre.webhook.office.com/webhookb2/5c49e775-13d2-4f6d-80b5-ba3f1651ebaf@38e68108-2383-4d82-a4b3-ac423a5e6218/IncomingWebhook/8c89ebe05dff443391f7c465b1ed1dee/dfd76bdb-37d4-4c4c-b907-6ea781954db5"
kubePrometheusStack:
  enabled: false
  prometheus:
    prometheusSpec:
      storageSpec:
        volumeClaimTemplate:
          spec:
            resources:
              requests:
                storage: 1Gi
  alertmanager:
    config:
      global:
        smtp_from: "Azure@gcatrans.com"